dist: trusty
sudo: false
addons:
  apt:
    packages:
    - texinfo
env:
  - EVM_VERSION=24.4
  - EVM_VERSION=24.5
  - EVM_VERSION=25.1
  - EVM_VERSION=25.2
  - EVM_VERSION=25.3

install:
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install emacs-$EVM_VERSION-travis
  - export PATH="/tmp/emacs-$EVM_VERSION-travis/bin:$PATH"

script:
  - make travis
