dist: trusty
sudo: required
addons:
  apt:
    packages:
      - texinfo
env:
  - EMACS_VERSION=24.4-travis
  - EMACS_VERSION=24.5-travis
  - EMACS_VERSION=25.1-travis
  - EMACS_VERSION=25.2-travis
  - EMACS_VERSION=25.3-travis
  - EMACS_VERSION=26.1-travis
  - EMACS_VERSION=git-snapshot

matrix:
  allow_failures:
    - env: EMACS_VERSION=git-snapshot

install:
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install emacs-$EMACS_VERSION
  - export PATH="/tmp/emacs-$EMACS_VERSION/bin:$PATH"

script:
  - make travis
