dist: trusty
sudo: false
install:
  - gem install evm
  - evm config path /tmp
  - evm install emacs-25.1-travis
  - export PATH="/tmp/emacs-25.1-travis/bin:$PATH"
  - emacs --version
script:
  - make travis
