version: 2
shared: &shared
  machine:
    image: ubuntu-1604:201903-01
  steps:
    - checkout
    # This command will pick up $VERSION from the environment.
    - run: >-
        make docker
        CMD="make -k compile checkdoc longlines checkindent smoke"
jobs:
  emacs-25.3:
    <<: *shared
    environment:
      VERSION: "25.3"
  emacs-26.3:
    <<: *shared
    environment:
      VERSION: "26.3"
  emacs-git:
    <<: *shared
    environment:
      VERSION: "master"
workflows:
  version: 2
  ci:
    jobs:
      - emacs-25.3
      - emacs-26.3
      - emacs-git
